# Generated by Django 2.2.1 on 2019-11-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_remove_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='images/01.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
