# Generated by Django 2.2.1 on 2019-11-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_goods_goods_description'),
        ('Buyer', '0002_auto_20191120_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.IntegerField(verbose_name='商品数量')),
                ('goods_total', models.FloatField(verbose_name='单件商品总价')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser', verbose_name='买家')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Goods', verbose_name='商品外键')),
            ],
            options={
                'verbose_name': '购物车表',
                'db_table': 'cart',
            },
        ),
    ]
