# Generated by Django 2.2.1 on 2019-11-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_goods_goods_description'),
        ('Buyer', '0005_validcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser'),
            preserve_default=False,
        ),
    ]
