# Generated by Django 2.2.1 on 2019-11-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_orderinfo_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payorder',
            name='order_address',
            field=models.IntegerField(default=0, verbose_name='订单收货地址'),
        ),
    ]
