# Generated by Django 2.2.1 on 2019-11-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lebal', models.CharField(max_length=32)),
                ('type_desciption', models.TextField()),
            ],
            options={
                'db_table': 'goodstype',
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(default='img/111.jpg', upload_to='img')),
                ('user_type', models.IntegerField(default=1, verbose_name='用户状态')),
            ],
            options={
                'db_table': 'loginuser',
            },
        ),
    ]
