# Generated by Django 2.2.1 on 2019-11-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='type_picture',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
