# Generated by Django 2.2.1 on 2019-11-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_useraddress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraddress',
            table='useraddress',
        ),
    ]
